<a href="https://colab.research.google.com/github/MonumentalCloud/Reinforced-Learning-Practice/blob/main/Q-Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import gym
import random

In [6]:
env = gym.make('Taxi-v3')
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [8]:
#creating q table

action_size = env.action_space.n
print("Action size ",  action_size)
state_size = env.observation_space.n
print("State size ", state_size)

Action size  6
State size  500


In [10]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [11]:
#hyperparameters

total_episodes = 50000
total_test_episodes = 100
max_steps = 99

learning_rate = 0.7
gamma = 0.618

#exploration rate
epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.01

In [12]:
for episode in range(total_episodes):
  state = env.reset()
  step = 0
  done = False

  for step in range(max_steps):
    exp_exp_tradeoff = random.uniform(0,1)

    #now, if tradeoff is bigger than the epsilon exploit according to the qtable
    if exp_exp_tradeoff > epsilon:
      action = np.argmax(qtable[state,:])
    
    #if not, do a random choice
    else:
      action = env.action_space.sample()
    
    new_state, reward, done, info = env.step(action)

    #bellman equation
    qtable[state,action] += learning_rate*(reward + np.max(qtable[new_state, :]) - qtable[state, action])

    state = new_state

    if done:
      break
    
    epsilon = min_epsilon + (max_epsilon-min_epsilon)*np.exp(-decay_rate*episode)

In [24]:
env.reset()
rewards = []
from IPython import display

for episode in range(total_test_episodes):
  state=env.reset()
  step = 0
  done = False
  total_rewards=0
  print("EPISODE ",episode )

  for step in range(max_steps):
    display.clear_output
    env.render()
    action = np.argmax(qtable[state, :])

    new_state, reward, done, info = env.step(action)

    total_rewards += reward

    if done:
      rewards.append(total_rewards)
      break
    
    state = new_state
env.close()

print("Score over time: " + str(sum(rewards)/total_test_episodes))


Streaming output truncated to the last 5000 lines.
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
EPISODE  52
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
|_| : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
|_: : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
|_: | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | 